#!/usr/bin/env python3
"""
EnvVault - Free CLI Tool #38
Manage environment variables across projects
Zero dependencies, single file, MIT licensed
https://github.com/barrowryan89-cloud/pd-researcher
"""

import os
import sys
import argparse
import json
from pathlib import Path
import shutil

__version__ = "1.0.0"

VAULT_DIR = Path.home() / ".envvault"
VAULT_FILE = VAULT_DIR / "vault.json"

def ensure_vault():
    """Ensure vault directory exists."""
    VAULT_DIR.mkdir(exist_ok=True)
    if not VAULT_FILE.exists():
        VAULT_FILE.write_text("{}")

def load_vault():
    """Load vault data."""
    ensure_vault()
    try:
        return json.loads(VAULT_FILE.read_text())
    except json.JSONDecodeError:
        return {}

def save_vault(data):
    """Save vault data."""
    ensure_vault()
    # Create backup
    if VAULT_FILE.exists():
        shutil.copy(VAULT_FILE, VAULT_FILE.with_suffix(".backup"))
    VAULT_FILE.write_text(json.dumps(data, indent=2))

def list_projects():
    """List all projects in vault."""
    vault = load_vault()
    if not vault:
        print("📭 No projects in vault")
        return
    
    print(f"\n📁 Environment Vault ({len(vault)} projects)\n")
    print(f"{'Project':<20} {'Variables':<10} {'Last Updated':<15}")
    print("-" * 50)
    
    for project, data in sorted(vault.items()):
        var_count = len(data.get("vars", {}))
        updated = data.get("updated", "Unknown")[:10]
        print(f"{project:<20} {var_count:<10} {updated:<15}")

def add_project(name, env_file=None):
    """Add a project to vault."""
    vault = load_vault()
    
    if name in vault:
        overwrite = input(f"⚠️  Project '{name}' exists. Overwrite? (y/N): ")
        if overwrite.lower() != 'y':
            print("Cancelled.")
            return
    
    vars_data = {}
    
    if env_file and os.path.exists(env_file):
        # Parse .env file
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    vars_data[key.strip()] = value.strip().strip('"\'')
        print(f"📥 Loaded {len(vars_data)} variables from {env_file}")
    else:
        # Interactive mode
        print(f"\n📝 Adding variables for '{name}'")
        print("Enter KEY=VALUE pairs (empty line to finish):")
        while True:
            entry = input("> ").strip()
            if not entry:
                break
            if '=' in entry:
                key, value = entry.split('=', 1)
                vars_data[key.strip()] = value.strip()
    
    from datetime import datetime
    vault[name] = {
        "vars": vars_data,
        "updated": datetime.now().isoformat()
    }
    save_vault(vault)
    print(f"✅ Saved {len(vars_data)} variables for '{name}'")

def show_project(name, export_format=None):
    """Show project variables."""
    vault = load_vault()
    
    if name not in vault:
        print(f"❌ Project '{name}' not found")
        print(f"💡 Use 'envvault list' to see available projects")
        return
    
    project = vault[name]
    vars_data = project.get("vars", {})
    
    if not vars_data:
        print(f"📭 No variables for '{name}'")
        return
    
    if export_format == "json":
        print(json.dumps(vars_data, indent=2))
    elif export_format == "export":
        for key, value in vars_data.items():
            print(f'export {key}="{value}"')
    else:
        print(f"\n🔐 {name} Environment Variables\n")
        print(f"{'Key':<25} {'Value':<30}")
        print("-" * 60)
        for key, value in sorted(vars_data.items()):
            # Mask sensitive values
            masked = value[:4] + "***" if len(value) > 8 else "***"
            if any(s in key.lower() for s in ['key', 'secret', 'password', 'token', 'api']):
                display = masked
            else:
                display = value[:30]
            print(f"{key:<25} {display:<30}")

def export_project(name, output=None):
    """Export project to .env file."""
    vault = load_vault()
    
    if name not in vault:
        print(f"❌ Project '{name}' not found")
        return
    
    vars_data = vault[name].get("vars", {})
    
    if not output:
        output = f"{name}.env"
    
    lines = [f"{key}={value}" for key, value in vars_data.items()]
    content = "# Generated by EnvVault\n" + "\n".join(lines) + "\n"
    
    with open(output, 'w') as f:
        f.write(content)
    
    print(f"✅ Exported to {output} ({len(vars_data)} variables)")

def delete_project(name):
    """Delete a project from vault."""
    vault = load_vault()
    
    if name not in vault:
        print(f"❌ Project '{name}' not found")
        return
    
    confirm = input(f"⚠️  Delete '{name}'? This cannot be undone. (type 'yes'): ")
    if confirm == "yes":
        del vault[name]
        save_vault(vault)
        print(f"✅ Deleted '{name}'")
    else:
        print("Cancelled.")

def search_variables(query):
    """Search across all projects for variables."""
    vault = load_vault()
    matches = []
    
    for project, data in vault.items():
        for key, value in data.get("vars", {}).items():
            if query.lower() in key.lower() or query.lower() in value.lower():
                matches.append((project, key, value))
    
    if not matches:
        print(f"🔍 No matches for '{query}'")
        return
    
    print(f"\n🔍 Found {len(matches)} matches for '{query}'\n")
    print(f"{'Project':<15} {'Key':<25} {'Value':<30}")
    print("-" * 75)
    for project, key, value in matches:
        display_val = value[:28] + ".." if len(value) > 30 else value
        print(f"{project:<15} {key:<25} {display_val:<30}")

def main():
    parser = argparse.ArgumentParser(
        description="EnvVault - Manage environment variables across projects",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s list                           List all projects
  %(prog)s add myapp --from .env          Import from .env file
  %(prog)s show myapp                     Display variables (masked)
  %(prog)s export myapp --output .env     Export to .env file
  %(prog)s search API_KEY                 Find variables across projects
  %(prog)s delete myapp                   Remove project from vault

Vault Location: ~/.envvault/vault.json
        """
    )
    
    parser.add_argument("action", choices=["list", "add", "show", "export", "delete", "search"],
                       help="Action to perform")
    parser.add_argument("project", nargs="?", help="Project name")
    parser.add_argument("--from", dest="env_file", help="Import from .env file")
    parser.add_argument("--output", "-o", help="Output file for export")
    parser.add_argument("--format", choices=["table", "json", "export"], default="table",
                       help="Output format for show command")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    
    args = parser.parse_args()
    
    print(f"""
╔═══════════════════════════════════════╗
║  EnvVault v{__version__} - Free CLI Tool #38        ║
║  https://pd-researcher.agent          ║
╚═══════════════════════════════════════╝
""")
    
    try:
        if args.action == "list":
            list_projects()
        elif args.action == "add":
            if not args.project:
                print("❌ Project name required")
                sys.exit(1)
            add_project(args.project, args.env_file)
        elif args.action == "show":
            if not args.project:
                print("❌ Project name required")
                sys.exit(1)
            show_project(args.project, args.format if args.format != "table" else None)
        elif args.action == "export":
            if not args.project:
                print("❌ Project name required")
                sys.exit(1)
            export_project(args.project, args.output)
        elif args.action == "delete":
            if not args.project:
                print("❌ Project name required")
                sys.exit(1)
            delete_project(args.project)
        elif args.action == "search":
            if not args.project:
                print("❌ Search query required")
                sys.exit(1)
            search_variables(args.project)
        
        print(f"\n💡 Upgrade to PD_Researcher Pro for:")
        print(f"   • Encrypted vault with password protection")
        print(f"   • Cloud sync across devices")
        print(f"   • Team sharing & permissions")
        print(f"   • https://pd-researcher.agent")
        
    except KeyboardInterrupt:
        print("\n\n⚠️  Cancelled")
        sys.exit(130)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()

    # Affiliate
    print("\n" + "-" * 60)
    print("🚀  Boost your productivity with these tools:")
    print("    • DigitalOcean: $200 free credit -> https://m.do.co/c/pdresearcher")
    print("    • JetBrains IDEs: The best Python tools -> https://www.jetbrains.com/?utm_source=pdresearcher")
    print("-" * 60)
